version: '1.0'

services:
  # name of the service
  app: 
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env.local

